BLOCK_DEFAULTS: dict[tuple[str, str], str] = {
    ("home", "hero_eyebrow"): "Заявки відкриті · сезон {year}",
    ("home", "marquee"): (
        "ОДИН ФУТБОЛ\n"
        "ЛЬВІВ 2026\n"
        "600+ ГРАВЦІВ\n"
        "ДЛЯ ДІТЕЙ ВІД 6 РОКів\n"
        "НАЙМАСОВІШІ ТУРНІРИ УКРАЇНИ"
    ),
    ("home", "stats_eyebrow"): "01 / Цифри сезону",
    ("home", "stats_title"): "Один рік. <span class=\"text-accent\">Пʼять турнірів.</span>",
    ("home", "stats_aside"): (
        "Команди з усієї України збираються у Львові пʼять разів на рік, "
        "щоб боротися за головний трофей."
    ),
    ("home", "stat_1_value"): "208",
    ("home", "stat_1_label"): "Команд за рік",
    ("home", "stat_1_hint"): "ACROSS 5 EVENTS",
    ("home", "stat_2_value"): "316",
    ("home", "stat_2_label"): "Матчів",
    ("home", "stat_2_hint"): "REGULAR + PLAYOFF",
    ("home", "stat_3_value"): "1381",
    ("home", "stat_3_label"): "Голів",
    ("home", "stat_3_hint"): "2025 SEASON",
    ("home", "stat_4_value"): "28",
    ("home", "stat_4_label"): "Міст-учасників",
    ("home", "stat_4_hint"): "UA + EU",
    ("home", "calendar_eyebrow"): "02 / Календар",
    ("home", "calendar_title"): "Календар сезону",
    ("home", "archive_eyebrow"): "03 / Архів",
    ("home", "archive_title"): "Минулі турніри",
    ("home", "archive_btn_all"): "Дивитись усе",
    ("home", "location_tag"): "ЛЬВІВ · UA · {year}",
    ("home", "label_dates"): "Дати",
    ("home", "label_teams"): "Команд",
    ("home", "label_location"): "Локація",
    ("home", "label_format"): "Формат",
    ("home", "soon_badge"): "Скоро",
    ("home", "hero_btn_detail"): "Перейти до турніру",
    ("home", "hero_btn_apply"): "Подати заявку",
    ("home", "hero_btn_soon"): "Скоро",
    ("home", "hero_swipe_touch"): "Свайпніть для зміни сезону",
    ("home", "hero_swipe_drag"): "Перетягніть для зміни сезону",
    ("home", "countdown_days"): "Дні",
    ("home", "countdown_hours"): "Год",
    ("home", "countdown_mins"): "Хв",
    ("home", "countdown_secs"): "Сек",
    ("home", "stat_plus"): "+",
    ("header", "cta_label"): "Подати заявку",
    ("footer", "about"): (
        "Наймасовіші футбольні турніри Західної України. "
        "Пʼять сезонів — пʼять фестивалів футболу для дітей від 6 років."
    ),
    ("footer", "copyright"): "© {year} Football Generation · ALL RIGHTS RESERVED",
    ("apply", "hero_eyebrow"): "· ЗАЯВКА КОМАНДИ ·",
    ("apply", "hero_title"): "Реєструйте<br><span class=\"text-accent\">команду</span>",
    ("apply", "hero_desc"): (
        "Заявка приймається лише від офіційних представників школи, академії або клубу. "
        "Після подання з вами зв'яжеться менеджер турніру."
    ),
    ("apply", "aside_eyebrow"): "Контакти",
    ("apply", "aside_title"): "Зв'яжіться з нами",
    ("apply", "aside_desc"): "Ми завжди готові відповісти на ваші питання щодо участі.",
    ("apply", "aside_phone_label"): "Телефон",
    ("apply", "aside_email_label"): "Email",
    ("apply", "aside_tournament_label"): "Обраний турнір",
    ("archive", "hero_eyebrow"): "03 / Архів",
    ("archive", "hero_title"): "Минулі<br><span class=\"text-accent\">турніри</span>",
    ("archive", "hero_desc"): (
        "Фото, цифри та моменти з минулих сезонів Football Generation. "
        "Пʼять турнірів на рік — одна історія футболу у Львові."
    ),
    ("archive", "editions_eyebrow"): "Сезони",
    ("archive", "editions_title"): "Результати<br><span class=\"text-accent\">за роки</span>",
    ("archive", "label_teams"): "Команд",
    ("archive", "label_matches"): "Матчів",
    ("archive", "label_goals"): "Голів",
    ("archive", "gallery_eyebrow"): "Галерея",
    ("archive", "gallery_title"): "Моменти<br><span class=\"text-accent\">з поля</span>",
    ("header", "nav_home"): "Головна",
    ("header", "nav_apply"): "Заявка",
    ("header", "nav_archive"): "Архів",
    ("header", "menu_sr_label"): "Меню",
    ("header", "nav_aria_label"): "Головна навігація",
    ("header", "wordmark_primary"): "Football",
    ("header", "wordmark_accent"): "Generation",
    ("footer", "col_tournaments"): "Турніри",
    ("footer", "col_contacts"): "Контакти",
    ("footer", "col_social"): "Соцмережі",
    ("footer", "tagline"): "ФУТБОЛЬНІ ТУРНІРИ · ЛЬВІВ",
    ("footer", "dev_credit_text"): "Сайт розроблено",
    ("apply", "form_tournament_eyebrow"): "01 / Турнір",
    ("apply", "form_tournament_title"): "Оберіть подію",
    ("apply", "form_team_eyebrow"): "02 / Команда",
    ("apply", "form_team_title"): "Дані команди",
    ("apply", "submit_btn"): "ПОДАТИ ЗАЯВКУ",
    ("apply", "form_error_title"): "Перевірте форму",
    ("apply", "form_error_desc"): "Заповніть усі обовʼязкові поля, позначені зірочкою (*).",
    ("apply", "required_error_msg"): "Заповніть це поле.",
    ("apply", "field_team_name_label"): "Назва команди",
    ("apply", "field_team_name_ph"): "Напр. ФК «Левеня»",
    ("apply", "field_age_category_label"): "Вікова категорія",
    ("apply", "field_age_category_ph"): "Напр. U-12",
    ("apply", "field_coach_name_label"): "Тренер / представник",
    ("apply", "field_coach_name_ph"): "ПІБ тренера",
    ("apply", "field_city_label"): "Місто",
    ("apply", "field_city_ph"): "Місто команди",
    ("apply", "field_players_count_label"): "Кількість гравців",
    ("apply", "field_phone_label"): "Номер телефону",
    ("apply", "field_phone_ph"): "+38 0XX XXX XX XX",
    ("apply", "field_email_label"): "E-mail",
    ("apply", "field_email_ph"): "email@club.ua",
    ("apply", "field_note_label"): "Додаткова інформація",
    ("apply", "field_note_ph"): "Додаткова інформація",
    ("apply", "success_eyebrow"): "· ЗАЯВКУ ПРИЙНЯТО ·",
    ("apply", "success_title_prefix"): "Дякуємо,",
    ("apply", "success_desc"): (
        "Ми зв'яжемося з вами протягом 24 годин для підтвердження участі у турнірі"
    ),
    ("apply", "success_btn_tournament"): "До сторінки турніру",
    ("apply", "success_btn_home"): "На головну",
    ("detail", "btn_all_tournaments"): "Всі турніри",
    ("detail", "about_eyebrow"): "01 / Про турнір",
    ("detail", "about_label_fee"): "Внесок",
    ("detail", "about_label_prizes"): "Нагороди",
    ("detail", "currency_suffix"): "₴",
    ("detail", "bracket_eyebrow"): "02 / Сітка",
    ("detail", "bracket_title"): "Плей-оф",
    ("detail", "bracket_qf"): "1/4 фіналу",
    ("detail", "bracket_sf"): "1/2 фіналу",
    ("detail", "bracket_final"): "Фінал",
    ("detail", "schedule_eyebrow"): "03 / Розклад",
    ("detail", "schedule_title"): "Матчі",
    ("detail", "col_day"): "День",
    ("detail", "col_time"): "Час",
    ("detail", "col_match"): "Матч",
    ("detail", "col_age"): "Вік",
    ("detail", "col_score"): "Рах.",
    ("detail", "col_field"): "Поле",
    ("detail", "stats_eyebrow"): "04 / Статистика",
    ("detail", "stats_title"): "Цифри та бомбардири",
    ("detail", "label_wins"): "Перемог",
    ("detail", "label_losses"): "Поразок",
    ("detail", "teams_eyebrow"): "05 / Команди",
    ("detail", "teams_title"): "Учасники",
    ("detail", "cta_eyebrow"): "· РЕЄСТРАЦІЯ ·",
    ("detail", "cta_title"): "Готові<br><span class=\"text-accent\">грати?</span>",
    ("detail", "cta_desc"): "Заявка приймається від офіційних представників школи або клубу.",
    ("site", "default_title"): "Football Generation — Футбольні турніри у Львові",
    ("site", "default_meta_description"): (
        "Футбольні турніри Football Generation у Львові — FG Spring Cup, FG Cup, FG Kids Cup."
    ),
    ("site", "brand_suffix"): "Football Generation",
    ("site", "home_page_title"): "Football Generation — Футбольні турніри у Львові",
    ("site", "apply_page_title"): "Заявка команди — Football Generation",
    ("site", "archive_page_title"): "Архів — Минулі турніри Football Generation",
    ("site", "wheel_prev_aria"): "Попередній сезон",
    ("site", "wheel_next_aria"): "Наступний сезон",
}
