# Generated by Django 6.0.5 on 2026-05-26 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+38 068 890 28 44', max_length=32)),
                ('email', models.EmailField(default='ruhcupleocup@gmail.com', max_length=254)),
                ('city', models.CharField(default='Львів, Україна', max_length=64)),
                ('url_instagram', models.URLField(blank=True)),
                ('url_telegram', models.URLField(blank=True)),
                ('url_youtube', models.URLField(blank=True)),
                ('url_tiktok', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=128)),
                ('season', models.CharField(max_length=32)),
                ('season_en', models.CharField(max_length=32)),
                ('year', models.CharField(default='2026', max_length=4)),
                ('theme_class', models.CharField(max_length=32)),
                ('dates_display', models.CharField(max_length=128)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
                ('teams_count', models.PositiveIntegerField()),
                ('matches_count', models.PositiveIntegerField()),
                ('goals_count', models.PositiveIntegerField()),
                ('age_groups', models.JSONField(default=list)),
                ('format_text', models.CharField(max_length=128)),
                ('prize', models.CharField(max_length=256)),
                ('fee_uah', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('highlight', models.CharField(max_length=256)),
                ('tagline', models.CharField(max_length=128)),
                ('icon_hint', models.CharField(blank=True, max_length=64)),
                ('hero_image', models.ImageField(blank=True, upload_to='tournaments/hero/')),
                ('card_image', models.ImageField(blank=True, upload_to='tournaments/cards/')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Турнір',
                'verbose_name_plural': 'Турніри',
                'ordering': ['sort_order', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('team_name', models.CharField(max_length=256, verbose_name='Назва команди')),
                ('age_category', models.CharField(max_length=128, verbose_name='Вікова категорія')),
                ('coach_name', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('players_count', models.PositiveSmallIntegerField(default=12)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('processed', 'Оброблена')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
