# Generated by Django 6.0.5 on 2026-05-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_sitesettings_social_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Рік')),
                ('title', models.CharField(max_length=64, verbose_name='Назва')),
                ('season', models.CharField(max_length=32, verbose_name='Сезон')),
                ('theme_class', models.CharField(choices=[('theme-spring', 'Весна — лайм'), ('theme-autumn', 'Осінь — янтар'), ('theme-winter', 'Зима — блакит'), ('theme-kids', 'Kids — червоний')], max_length=32, verbose_name='Кольорова гама')),
                ('teams_count', models.PositiveIntegerField(verbose_name='Команд')),
                ('matches_count', models.PositiveIntegerField(verbose_name='Матчів')),
                ('goals_count', models.PositiveIntegerField(verbose_name='Голів')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Архівний турнір',
                'verbose_name_plural': 'Архівні турніри',
                'ordering': ['-year', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Зображення')),
                ('alt_text', models.CharField(max_length=256, verbose_name='Alt-текст')),
                ('label', models.CharField(blank=True, max_length=128, verbose_name='Підпис')),
                ('height', models.PositiveSmallIntegerField(choices=[(240, '240 px'), (320, '320 px')], default=240, verbose_name='Висота блоку')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('show_on_home', models.BooleanField(default=False, verbose_name='На головній')),
                ('show_on_archive', models.BooleanField(default=True, verbose_name='В архіві')),
            ],
            options={
                'verbose_name': 'Зображення галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='losses_count',
            field=models.PositiveIntegerField(blank=True, help_text='Залиште порожнім, щоб приховати на сайті до внесення результатів.', null=True, verbose_name='Поразок'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='match_duration_minutes',
            field=models.PositiveSmallIntegerField(default=20, help_text='Використовується у форматі турніру на сайті.', verbose_name='Тривалість тайму (хв)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='application',
            name='coach_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='players_count',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Кількість гравців'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('processed', 'Оброблена')], default='new', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='tournaments.tournament', verbose_name='Турнір'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='city',
            field=models.CharField(default='Львів, Україна', max_length=64, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='ruhcupleocup@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='+38 068 890 28 44', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='url_instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='url_telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='url_tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='url_youtube',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='age_groups',
            field=models.JSONField(blank=True, default=list, help_text='Застаріле поле. Краще додавати вікові групи у вкладці нижче.', verbose_name='Вікові групи (legacy JSON)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='tournaments/cards/', verbose_name='Зображення картки'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='dates_display',
            field=models.CharField(max_length=128, verbose_name='Дати (текст)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='fee_uah',
            field=models.CharField(max_length=16, verbose_name='Внесок (₴)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format_text',
            field=models.CharField(max_length=128, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='tournaments/hero/', verbose_name='Hero-зображення'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='highlight',
            field=models.CharField(max_length=256, verbose_name='Акцент'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='icon_hint',
            field=models.CharField(blank=True, max_length=64, verbose_name='Підказка іконки'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='location',
            field=models.CharField(max_length=256, verbose_name='Локація'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='matches_count',
            field=models.PositiveIntegerField(verbose_name='Матчів (на сайті)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='prize',
            field=models.CharField(max_length=256, verbose_name='Нагороди'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season',
            field=models.CharField(max_length=32, verbose_name='Сезон (UA)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season_en',
            field=models.CharField(choices=[('Spring', 'Весна'), ('Autumn', 'Осінь'), ('Winter', 'Зима'), ('Kids', 'Kids')], help_text='Визначає іконку сезону на сайті.', max_length=32, verbose_name='Сезон (іконка)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Початок'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='subtitle',
            field=models.CharField(max_length=128, verbose_name='Підзаголовок'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tagline',
            field=models.CharField(max_length=128, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams_count',
            field=models.PositiveIntegerField(verbose_name='Команд (на сайті)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='theme_class',
            field=models.CharField(choices=[('theme-spring', 'Весна — лайм'), ('theme-autumn', 'Осінь — янтар'), ('theme-winter', 'Зима — блакит'), ('theme-kids', 'Kids — червоний')], help_text='Акцентний колір сторінки турніру на сайті.', max_length=32, verbose_name='Кольорова гама'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='year',
            field=models.CharField(default='2026', max_length=4, verbose_name='Рік'),
        ),
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Назва')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_groups_rel', to='tournaments.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Вікова група',
                'verbose_name_plural': 'Вікові групи',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Назва')),
                ('city', models.CharField(max_length=128, verbose_name='Місто')),
                ('short_code', models.CharField(max_length=8, verbose_name='Код')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Перемоги')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Поразки')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament', verbose_name='Турнір')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команди',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Повне імʼя')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='tournaments.agegroup', verbose_name='Вікова група')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Гравець',
                'verbose_name_plural': 'Гравці',
                'ordering': ['sort_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(default=1, verbose_name='День')),
                ('time', models.TimeField(verbose_name='Час')),
                ('field', models.CharField(max_length=64, verbose_name='Поле')),
                ('score_home', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Голи (госп.)')),
                ('score_away', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Голи (гості)')),
                ('stage', models.CharField(choices=[('group', 'Груповий етап'), ('r16', '1/8 фіналу'), ('sf', '1/2 фіналу'), ('final', 'Фінал')], default='group', max_length=16, verbose_name='Етап')),
                ('status', models.CharField(choices=[('upcoming', 'Майбутній'), ('live', 'Live'), ('finished', 'Завершено')], default='upcoming', max_length=16, verbose_name='Статус')),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.agegroup', verbose_name='Вікова група')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament', verbose_name='Турнір')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournaments.team', verbose_name='Гості')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournaments.team', verbose_name='Господарі')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчі',
                'ordering': ['day', 'time', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveSmallIntegerField(verbose_name='Хвилина')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tournaments.match', verbose_name='Матч')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='tournaments.player', verbose_name='Гравець')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tournaments.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Гол',
                'verbose_name_plural': 'Голи',
                'ordering': ['minute', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='agegroup',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_age_group_per_tournament'),
        ),
    ]
