# Generated by Django 5.2.15 on 2026-06-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_gallery_show_on_home_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(blank=True, default='Наймасовіші футбольні турніри Західної України. Чотири сезони — чотири фестивалі футболу для дітей від 6 років.', verbose_name='Текст про організацію (footer)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© {year} Football Generation · ALL RIGHTS RESERVED', help_text='Використовуйте {year} для поточного року.', max_length=256, verbose_name='Copyright (footer)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='header_cta_label',
            field=models.CharField(default='Подати заявку', max_length=64, verbose_name='Текст кнопки в хедері'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Якщо порожньо — використовується стандартний логотип Football Generation.', upload_to='site/', verbose_name='Логотип (override)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Football Generation', max_length=128, verbose_name='Назва сайту'),
        ),
        migrations.AlterField(
            model_name='archiveedition',
            name='theme_class',
            field=models.CharField(choices=[('theme-spring', 'Весна — лайм'), ('theme-autumn', 'Осінь — бурштин'), ('theme-winter', 'Зима — блакитний'), ('theme-kids', 'Kids — червоний')], max_length=32, verbose_name='Кольорова гама'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='diegomara@ukr.net', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='theme_class',
            field=models.CharField(choices=[('theme-spring', 'Весна — лайм'), ('theme-autumn', 'Осінь — бурштин'), ('theme-winter', 'Зима — блакитний'), ('theme-kids', 'Kids — червоний')], help_text='Акцентний колір сторінки турніру на сайті.', max_length=32, verbose_name='Кольорова гама'),
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна'), ('header', 'Хедер'), ('footer', 'Футер'), ('apply', 'Заявка'), ('archive', 'Архів')], max_length=32, verbose_name='Сторінка')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ блоку')),
                ('label', models.CharField(max_length=128, verbose_name='Назва в адмінці')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Фото'), ('video', 'Відео')], default='text', max_length=16, verbose_name='Тип контенту')),
                ('text_html', models.TextField(blank=True, verbose_name='Текст (HTML)')),
                ('image', models.ImageField(blank=True, upload_to='blocks/', verbose_name='Зображення')),
                ('video_url', models.URLField(blank=True, verbose_name='URL відео (YouTube/Vimeo)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Блок контенту',
                'verbose_name_plural': 'Блоки контенту',
                'ordering': ['page', 'sort_order', 'key'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_site_block_page_key')],
            },
        ),
    ]
