# Generated by Django 5.2.15 on 2026-06-10 07:27

from datetime import datetime, timezone as dt_timezone

from django.db import migrations, models


SUMMER_TOURNAMENT = {
    "slug": "fg-summer-cup",
    "title": "FG SUMMER CUP",
    "subtitle": "Summer Edition",
    "season": "Літо",
    "season_en": "Summer",
    "year": "2026",
    "theme_class": "theme-summer",
    "dates_display": "10 — 12 липня 2026",
    "location": "СК «Сокіл», Львів",
    "teams_count": 52,
    "matches_count": 78,
    "format_text": "7+1, два тайми по 20 хв",
    "prize": "Кубки + медалі + MVP турніру",
    "fee_uah": "4 100",
    "description": (
        "Літня серія Football Generation на відкритому полі. "
        "Інтенсивний футбол під сонцем — головний виклик сезону для юних гравців."
    ),
    "highlight": "Літній футбол на відкритому повітрі",
    "tagline": "Гаряче літо на полі",
    "icon_hint": "SUN · GOLD",
    "is_published": True,
    "sort_order": 2,
    "match_duration_minutes": 20,
    "age_groups": ["U-9", "U-10", "U-11", "U-12", "U-13"],
}

SORT_ORDER_UPDATES = {
    "leo-cup": 1,
    "fg-summer-cup": 2,
    "leo-cup-osen": 3,
    "ruh-cup": 4,
    "ruh-kids-cup": 5,
}


def add_summer_season(apps, schema_editor):
    Tournament = apps.get_model("tournaments", "Tournament")
    ArchiveEdition = apps.get_model("tournaments", "ArchiveEdition")

    if not Tournament.objects.filter(slug="fg-summer-cup").exists():
        Tournament.objects.create(
            **SUMMER_TOURNAMENT,
            starts_at=datetime(2026, 7, 10, 6, 0, tzinfo=dt_timezone.utc),
            ends_at=datetime(2026, 7, 12, 20, 0, tzinfo=dt_timezone.utc),
        )

    for slug, sort_order in SORT_ORDER_UPDATES.items():
        Tournament.objects.filter(slug=slug).update(sort_order=sort_order)

    if not ArchiveEdition.objects.filter(title="FG SUMMER CUP", season="Літо").exists():
        ArchiveEdition.objects.create(
            year="2025",
            title="FG SUMMER CUP",
            season="Літо",
            theme_class="theme-summer",
            teams_count=52,
            matches_count=68,
            goals_count=290,
            sort_order=2,
            is_published=True,
        )


def remove_summer_season(apps, schema_editor):
    Tournament = apps.get_model("tournaments", "Tournament")
    ArchiveEdition = apps.get_model("tournaments", "ArchiveEdition")
    Tournament.objects.filter(slug="fg-summer-cup").delete()
    ArchiveEdition.objects.filter(title="FG SUMMER CUP", season="Літо").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_rebrand_and_seed_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveedition',
            name='theme_class',
            field=models.CharField(choices=[('theme-spring', 'Весна — лайм'), ('theme-summer', 'Літо — сонячний'), ('theme-autumn', 'Осінь — бурштин'), ('theme-winter', 'Зима — блакитний'), ('theme-kids', 'Kids — червоний')], max_length=32, verbose_name='Кольорова гама'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_about',
            field=models.TextField(blank=True, default='Наймасовіші футбольні турніри Західної України. Пʼять сезонів — пʼять фестивалів футболу для дітей від 6 років.', verbose_name='Текст про організацію (footer)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season_en',
            field=models.CharField(choices=[('Spring', 'Весна'), ('Summer', 'Літо'), ('Autumn', 'Осінь'), ('Winter', 'Зима'), ('Kids', 'Kids')], help_text='Визначає іконку сезону на сайті.', max_length=32, verbose_name='Сезон (іконка)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='theme_class',
            field=models.CharField(choices=[('theme-spring', 'Весна — лайм'), ('theme-summer', 'Літо — сонячний'), ('theme-autumn', 'Осінь — бурштин'), ('theme-winter', 'Зима — блакитний'), ('theme-kids', 'Kids — червоний')], help_text='Акцентний колір сторінки турніру на сайті.', max_length=32, verbose_name='Кольорова гама'),
        ),
        migrations.RunPython(add_summer_season, remove_summer_season),
    ]
